Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S,M,L)
  DatabaseName:
    Type: String
    Default: wordpress
  DatabaseUser:
    Type: String
    Default: wordpress
  DatabasePassword:
    Type: String
    Default: w0rdpr355
    NoEcho: true
Mappings:
  RegionMap:
    us-east-1:
      "AMALINUX" : "ami-1853ac65" # AMALINUX SEP 2016
    us-east-2:
      "AMALINUX" : "ami-25615740" # AMALINUX SEP 2016
    us-west-1:
      "AMALINUX" : "ami-bf5540df" # AMALINUX SEP 2016
    us-west-2:
      "AMALINUX" : "ami-d874e0a0" # AMALINUX SEP 2016
    ca-central-1:
      "AMALINUX" : "ami-5b55d23f" # AMALINUX SEP 2016 v01
    eu-west-1:
      "AMALINUX" : "ami-3bfab942" # AMALINUX SEP 2016
    eu-central-1:
      "AMALINUX" : "ami-ac442ac3" # AMALINUX SEP 2016
    eu-west-2:
      "AMALINUX" : "ami-dff017b8" # AMALINUX SEP 2016 v01
    eu-west-3:
      "AMALINUX" : "ami-4f55e332" # AMALINUX SEP 2016 v01
    ap-southeast-1:
      "AMALINUX" : "ami-e2adf99e" # AMALINUX SEP 2016
    ap-southeast-2:
      "AMALINUX" : "ami-43874721" # AMALINUX SEP 2016
    ap-northeast-2:
      "AMALINUX" : "ami-5e1ab730" # AMALINUX SEP 2016
    ap-northeast-1:
      "AMALINUX" : "ami-a77c30c1" # AMALINUX SEP 2016
    ap-south-1:
      "AMALINUX" : "ami-7c87d913" # AMALINUX SEP 2016
    sa-east-1:
      "AMALINUX" : "ami-5339733f" # AMALINUX SEP 2016
  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
      "DB" : "db.t2.small"
    LARGE:
      "EC2" : "t2.medium"
      "DB" : "db.t2.medium"
Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB] # Dynamic mapping + Pseudo Parameter
      DBName: !Ref DatabaseName
      Engine: MySQL
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX] # Dynamic mapping + Pseudo Parameter
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      KeyName: AdvancedCFN
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd php mysql php-mysql -y
            yum update -y
            chkconfig httpd on
            service httpd start
            cd /var/www/html
            wget https://wordpress.org/latest.tar.gz
            tar -zxvf latest.tar.gz --strip 1
            rm latest.tar.gz
            cp wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
            sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
  S3:
    Type: "AWS::S3::Bucket"
