Resources:
   DB:
      Type: "AWS::RDS::DBInstance"
      Properties:
         AllocatedStorage: 5
         DBInstanceClass: db.t2.micro
         DBName: wordpress
         StorageType: gp2
         Engine: MySQL
         MasterUsername: wordpress
         MasterUserPassword: wordpress
   EC2:
      Type: "AWS::EC2::Instance"
      Properties:
         ImageId: ami-d874e0a0
         InstanceType: t2.micro
   S3:
      Type: "AWS::S3::Bucket"
      Properties:
         BucketName: wp-148437
