Resources:
   DB:
      Type: "AWS::RDS::DBInstance"
      Properties:
         AllocatedStorage: 5
         DBInstanceClass: !FindInMap [EnvSize, !Ref EnvironmentSize, DB]
         DBName: wordpress
         StorageType: gp2
         Engine: MySQL
         MasterUsername: wordpress
         MasterUserPassword: wordpress
   EC2:
      Type: "AWS::EC2::Instance"
      Properties:
         ImageId: ami-d874e0a0
         InstanceType: !FindInMap [EnvSize, !Ref EnvironmentSize, EC2]
         SubnetId: subnet-9fbf6ed7
   S3:
      Type: "AWS::S3::Bucket"
      Properties:
         BucketName: !Ref BucketName
Mappings:
   EnvSize:
      SMALL:
         "EC2": "t2.micro"
         "DB": "db.t2.micro"
      MEDIUM:
         "EC2": "t2.small"
         "DB": "db.t2.small"
      LARGE:
         "EC2": "t2.medium"
         "DB": "db.t2.medium"
Parameters:
   EnvironmentSize:
      Type: String
      Default: "MEDIUM"
      AllowedValues:
        - "SMALL"
        - "MEDIUM"
        - "LARGE"
      Description: Environment sizes
   BucketName:
      Type: String

