Resources:
   DB:
      Type: "AWS::RDS::DBInstance"
      Properties:
         AllocatedStorage: 5
         DBInstanceClass: db.t2.micro
         DBName: wordpress
         StorageType: gp2
         Engine: MySQL
         MasterUsername: wordpress
         MasterUserPassword: wordpress
   EC2:
      Type: "AWS::EC2::Instance"
      Properties:
         ImageId: ami-d874e0a0
         InstanceType: t2.micro
         SubnetId: subnet-9fbf6ed7
   S3:
      Type: "AWS::S3::Bucket"
      Properties:
         BucketName: wp-148437
Parameters:
   Instancesize:
      Type: String
      Default: t2.micro
      AllowedValues:
        - t2.micro
        - t2.small
        - t2.medium
      Description: Instance sizes
